### ISSUE TITLE
Issue with reproducing pretraining

### ISSUE THREAD

**Issue by ta012** [cwx-worst-one/EAT#4]
Hi, Great work! I pre-trained the network using the provided script with the full AudioSet (unbalanced + balanced), similar to BEATs and AudioMAE. So my pre-training set is slightly larger than yours (1.93M samples). I trained for 10 epochs (40K updates) using the provided script. However, I am unable to reproduce the reported AS20K performance, achieving only around 35.8 mAP compared to the reported 40.2 mAP. I fine-tuned on AS20K using the shared pre-trained weights(EAT-base_epoch10.pt) and achieved the reported performance, so I don't think there is an issue with the dataset. Am I missing something here?

**Comment by cwx-worst-one** [comment]
Thanks for following our work!

Here are some possible reasons or advice:

1. Have you checked your pre-training [script](https://github.com/cwx-worst-one/EAT/blob/main/scripts/pretraining_AS2M.sh) and [configs](https://github.com/cwx-worst-one/EAT/blob/main/config/pretraining_AS2M.yaml) to ensure they are the same as ours? Minor differences can lead to significant variations in pre-training results.

2. Make sure your PyTorch version matches the one specified in our [requirements.txt](https://github.com/cwx-worst-one/EAT/blob/main/requirements.txt). Some users have experienced reproducing failures using older versions of PyTorch (e.g., 1.x). Additionally, we did not use the Apex library for acceleration in our experiments.

3. You can compare and validate your results with our training logs available here in [wandb](https://wandb.ai/wxc12/EAT/reports/EAT-Self-Supervised-Pre-Training-with-Efficient-Audio-Transformer--Vmlldzo2OTI4MTUx?accessToken=b61ab72qi09t2n2vn5irqzsq4bsuvyrl6l0z3mtsxau0fft0eiq2z4ckmn0jz787).


Feel free to reach out if you have any other questions!
