### ISSUE TITLE
关于feature_extract的请教

### ISSUE THREAD

**Issue by zhangron013** [cwx-worst-one/EAT#6]
您好，我想请教一下feature_extract.py对应的是否是EAT作为Audio Encoder的输出？
我运行feature_extract.py之后输出是一个[512,1024]的tensor。实际上我想用EAT做编码器用于AAC任务，我直接复用feature_extract方法可以吗？
我了解到贵团队的“SLAM-LLM”已经在此基础上集成了该功能，其中示例`examples/aac_audiocaps/scripts/inference_eat_audiocaps.sh`的line31:    `++model_config.encoder_dim=768`。一些其他的工作如HTSAT的输出也是768，我想请教一下这里为什么把模型的输出设置为768？
我打印了模型的结构：
```python
(IMAGE): ImageEncoder(
      (local_encoder): PatchEmbed_new(
        (proj): Conv2d(1, 1024, kernel_size=(16, 16), stride=(16, 16))
      )
      (project_features): Identity()
      (fixed_positional_encoder): FixedPositionalEncoder()
      (context_encoder): BlockEncoder(
        (blocks): ModuleList()
        (norm): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
        (dropout): Dropout(p=0.0, inplace=True)
      )
      (decoder): None
    )
  )
``` 
我的理解是encoder_dim=768会导致EAT的输出是一个[bs,patch,768]的tensor，我这样理解正确吗？

**Comment by cwx-worst-one** [comment]
因为 SLAM-LLM 中默认使用的 audio encoder 是 base 大小的，所以 embedding 维度设置成了 768。你这里的 embedding 维度是 1024 是因为使用了 EAT-large 的 checkpoint。你可以使用 EAT-base 的 checkpoint 来应用到 SLAM-LLM 框架上，或者你用当前的 EAT-large 时修改 SLAM-LLM 中的脚本参数设置，比如 `++model_config.encoder_dim=1024` 等。

**Comment by zhangron013** [comment]
理解了，thanks~
