### ISSUE TITLE
How can I set the number of epochs?

### ISSUE THREAD

**Issue by WGook** [cwx-worst-one/EAT#8]
Hi, while I'm trying to run the script, I cannot find which script should I modify to change the number of epochs. How can I set the number of epochs?

**Comment by cwx-worst-one** [comment]
Hi, to set the number of epochs, you can modify the script by referencing the settings in the configuration files located in `EAT/config/xxx`. For example, you can add a line like `optimization.max_update=xxx` directly in the script to adjust the training steps during pre-training or fine-tuning, ensuring it aligns with your desired number of epochs. 

Alternatively, you can directly modify the settings in the configuration files themselves to achieve the same effect.
