### ISSUE TITLE
Finetuning on own dataset

### ISSUE THREAD

**Issue by cvillela** [cwx-worst-one/EAT#9]
Hey there!

Congratulations on the model and thanks for open sourcing!

I would like to finetune EAT on my own dataset for audio classification. Is it possible?

If so, would the best pipeline be to just classify from the latent representations of the model using a shallow head? Or to fine-tune the whole model (or last layers) on a new dataset?

If finetuning the whole model, is it possible to freeze early layers and just adjust the last layer's weights? What would be your approach?

Thank you so much for your effort!

**Comment by cwx-worst-one** [comment]
Yes, it is definitely possible! We have fine-tuned EAT (the pre-trained version) on other classification datasets like ESC-50 and SPC-2, and have evaluated its generalizability.

Based on my experience, fine-tuning the entire model on the new dataset tends to yield better results compared to other strategies. It is feasible to only train the last few layers, but in my previous experiments, this approach didn’t perform as well as full model fine-tuning.

I hope this helps!

**Comment by cvillela** [comment]
Thank you so much for the response, will be closing this issue and experiment !

**Comment by cvillela** [comment]
Hello, would you have a script for finetuning on own data? I realize there are the premade scripts for specific datasets, but no open ended version

**Comment by cwx-worst-one** [comment]
Apologies, but at the moment, we do not have a script specifically designed for open-ended finetuning. However, you can customize your own version by referencing the code we have provided for handling specific datasets.
